version: 2

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
        
    - path: testdata/
      linters:
        - errcheck
        - staticcheck

  max-issues-per-linter: 0
  max-same-issues: 0
